#!/usr/bin/env python3
"""Generate per-residue ESM-1b embeddings for retrieval train/val sequences.

This script reads `train.fasta` and `val.fasta` from a dataset directory
generated by `download_structures.py`, then writes one `.npy` file per
sequence ID:

    <output_dir>/<sequence_id>.npy

Each file contains a float32 array with shape:
    [L, D] where D=1280 for ESM-1b and L<=truncation_seq_length.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np
import torch
from torch.utils.data import DataLoader

try:
    from esm import FastaBatchedDataset, pretrained
except Exception as exc:  # pragma: no cover
    raise RuntimeError(
        "Failed to import esm package. Install fair-esm in the active environment."
    ) from exc


logger = logging.getLogger(__name__)


def parse_fasta(path: Path) -> List[Tuple[str, str]]:
    records: List[Tuple[str, str]] = []
    header = None
    chunks: List[str] = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith(">"):
                if header is not None:
                    records.append((header, "".join(chunks)))
                header = line[1:].split()[0]
                chunks = []
            else:
                chunks.append(line)
    if header is not None:
        records.append((header, "".join(chunks)))
    return records


def sanitize_sequence(seq: str) -> str:
    seq = seq.upper()
    # Keep amino-acid letters; replace any unexpected symbol with X.
    return re.sub(r"[^A-Z]", "X", seq)


def load_split_sequences(dataset_dir: Path) -> Tuple[List[Tuple[str, str]], Dict[str, str]]:
    train_fasta = dataset_dir / "train.fasta"
    val_fasta = dataset_dir / "val.fasta"
    if not train_fasta.exists() or not val_fasta.exists():
        raise FileNotFoundError(
            f"Expected train/val FASTA in {dataset_dir}, missing one of: {train_fasta}, {val_fasta}"
        )

    split_by_id: Dict[str, str] = {}
    all_records: List[Tuple[str, str]] = []

    for split, fasta_path in (("train", train_fasta), ("val", val_fasta)):
        for seq_id, seq in parse_fasta(fasta_path):
            seq = sanitize_sequence(seq)
            if seq_id in split_by_id and split_by_id[seq_id] != split:
                raise ValueError(
                    f"Sequence ID {seq_id!r} appears in both {split_by_id[seq_id]} and {split} FASTA"
                )
            split_by_id[seq_id] = split
            all_records.append((seq_id, seq))

    return all_records, split_by_id


def build_pending_records(
    records: Sequence[Tuple[str, str]],
    output_dir: Path,
    overwrite: bool,
    max_sequences: int,
) -> List[Tuple[str, str]]:
    pending: List[Tuple[str, str]] = []
    for seq_id, seq in records:
        out_path = output_dir / f"{seq_id}.npy"
        if not overwrite and out_path.exists():
            continue
        pending.append((seq_id, seq))
        if max_sequences > 0 and len(pending) >= max_sequences:
            break
    return pending


def resolve_device(device_arg: str) -> torch.device:
    if device_arg == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device_arg == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("Requested --device cuda but CUDA is not available")
    return torch.device(device_arg)


def generate_embeddings(
    records: Sequence[Tuple[str, str]],
    output_dir: Path,
    model_name: str,
    repr_layer: int,
    toks_per_batch: int,
    truncation_seq_length: int,
    device: torch.device,
) -> Dict[str, object]:
    if not records:
        return {"num_written": 0}

    # ESM-1b default checkpoint name in fair-esm.
    if model_name != "esm1b_t33_650M_UR50S":
        logger.warning("Using non-default ESM model name: %s", model_name)

    logger.info("Loading model: %s", model_name)
    model, alphabet = pretrained.load_model_and_alphabet(model_name)
    model.eval()
    model = model.to(device)
    embed_dim = 1280
    logger.info("Model loaded on %s (embed_dim=%d)", device, embed_dim)

    labels = [r[0] for r in records]
    seqs = [r[1] for r in records]
    seq_by_id = {sid: seq for sid, seq in records}

    dataset = FastaBatchedDataset(labels, seqs)
    batches = dataset.get_batch_indices(toks_per_batch=toks_per_batch, extra_toks_per_seq=1)
    loader = DataLoader(
        dataset,
        batch_sampler=batches,
        collate_fn=alphabet.get_batch_converter(truncation_seq_length=truncation_seq_length),
    )

    written = 0
    with torch.no_grad():
        for batch_labels, batch_strs, batch_tokens in loader:
            batch_tokens = batch_tokens.to(device=device, non_blocking=True)
            out = model(batch_tokens, repr_layers=[repr_layer], return_contacts=False)
            reps = out["representations"][repr_layer].cpu()

            for i, seq_id in enumerate(batch_labels):
                seq_len = min(len(seq_by_id[seq_id]), truncation_seq_length)
                # Drop BOS/EOS tokens. Per-residue representation length = seq_len.
                residue_reps = reps[i, 1 : 1 + seq_len].numpy().astype(np.float32, copy=False)
                np.save(output_dir / f"{seq_id}.npy", residue_reps)
                written += 1

    return {"num_written": written, "embed_dim": embed_dim}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate per-residue ESM-1b embeddings for train/val FASTA sequences"
    )
    parser.add_argument("--dataset_dir", type=Path, required=True, help="Directory with train.fasta and val.fasta")
    parser.add_argument("--output_dir", type=Path, required=True, help="Output directory for <sequence_id>.npy files")
    parser.add_argument("--model_name", type=str, default="esm1b_t33_650M_UR50S")
    parser.add_argument("--repr_layer", type=int, default=33)
    parser.add_argument("--toks_per_batch", type=int, default=4096)
    parser.add_argument("--truncation_seq_length", type=int, default=1022)
    parser.add_argument("--device", type=str, choices=["auto", "cuda", "cpu"], default="auto")
    parser.add_argument("--overwrite", action="store_true", help="Regenerate even if output file exists")
    parser.add_argument("--max_sequences", type=int, default=0, help="Optional cap for smoke tests/debug")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    records, split_by_id = load_split_sequences(args.dataset_dir)
    pending = build_pending_records(
        records=records,
        output_dir=args.output_dir,
        overwrite=args.overwrite,
        max_sequences=args.max_sequences,
    )

    logger.info("Total records: %d (train=%d, val=%d)", len(records),
                sum(1 for sid in split_by_id if split_by_id[sid] == "train"),
                sum(1 for sid in split_by_id if split_by_id[sid] == "val"))
    logger.info("Pending for embedding: %d (overwrite=%s)", len(pending), args.overwrite)

    if not pending:
        logger.info("Nothing to do.")
        return

    device = resolve_device(args.device)
    stats = generate_embeddings(
        records=pending,
        output_dir=args.output_dir,
        model_name=args.model_name,
        repr_layer=args.repr_layer,
        toks_per_batch=args.toks_per_batch,
        truncation_seq_length=args.truncation_seq_length,
        device=device,
    )

    meta = {
        "dataset_dir": str(args.dataset_dir),
        "output_dir": str(args.output_dir),
        "model_name": args.model_name,
        "repr_layer": args.repr_layer,
        "toks_per_batch": args.toks_per_batch,
        "truncation_seq_length": args.truncation_seq_length,
        "device": str(device),
        "num_records_total": len(records),
        "num_records_pending": len(pending),
        "num_records_written": int(stats.get("num_written", 0)),
        "embed_dim": int(stats.get("embed_dim", 0)),
    }
    meta_path = args.output_dir / "esm1b_embedding_metadata.json"
    meta_path.write_text(json.dumps(meta, indent=2))
    logger.info("Done. Wrote metadata: %s", meta_path)


if __name__ == "__main__":
    main()
